// Expressive Developer Emoji & Glyph Suite for GITBOT
// Vibrant, colorful, and supported across Discord Desktop, Web, iOS, and Android.

export const NF = {
  // Brand & Git
  github: "🐙",
  gitBranch: "🌿",
  gitCommit: "📜",
  gitPullRequest: "🔀",
  gitMerge: "🔀",
  gitTag: "🏷️",
  gitFork: "🍴",
  issue: "🐞",
  bug: "🐛",

  // Status & Telemetry
  check: "✅",
  cross: "❌",
  warning: "⚠️",
  spinner: "⏳",
  star: "⭐",
  flame: "🔥",
  clock: "⏱️",
  speedometer: "📈",
  package: "📦",
  terminal: "💻",
  document: "📄",
  search: "🔍",
  shield: "🛡️",
  network: "🌐",
  heart: "❤️",
  user: "👤",
  users: "👥",
  bullet: "•",
  arrowRight: "➔",
  robot: "🤖",
  sparkle: "✨",
  chat: "💬",
  rocket: "🚀",
  tools: "🛠️",
  bell: "🔔",
  lock: "🔐",
  unlock: "🔓",
  greenDot: "🟢",
  yellowDot: "🟡",
  redDot: "🔴",
} as const;
